In [2]:
import pandas as pd
data = pd.read_csv('Cleaned-Data.csv')
data.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
0,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,0,1,China
1,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,0,China
2,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,1,0,0,China
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,0,1,China
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,1,0,China

In [7]:
sevmild=data.replace({'Severity_Mild': 1}, 20)
sevmod=sevmild.replace({'Severity_Moderate': 1}, 30)
sevnone=sevmod.replace({'Severity_None': 1}, 10)
datanew=sevnone.replace({'Severity_Severe': 1}, 40)
datanew['Severity']=datanew['Severity_Mild']+datanew['Severity_Moderate']+datanew['Severity_None']+datanew['Severity_Severe']
datanew.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Severity
0,1,1,1,1,1,0,1,1,1,1,...,0,20,0,0,0,0,0,1,China,20
1,1,1,1,1,1,0,1,1,1,1,...,0,20,0,0,0,0,1,0,China,20
2,1,1,1,1,1,0,1,1,1,1,...,0,20,0,0,0,1,0,0,China,20
3,1,1,1,1,1,0,1,1,1,1,...,0,0,30,0,0,0,0,1,China,30
4,1,1,1,1,1,0,1,1,1,1,...,0,0,30,0,0,0,1,0,China,30

Legenda: Severity_None - 10 | Severity_Mild - 20 | Severity_Moderate - 30 | Severity_Severe - 40

In [9]:
train = datanew.drop(['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe','Country'],axis=1)
label = datanew['Severity']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, label, test_size=0.30, random_state=101)

In [17]:
#SVM

from sklearn import svm
from sklearn.model_selection import train_test_split

clf = svm.SVC(gamma=0.0001)

clf.fit(X_train,y_train)
#Prediction
predictions = clf.predict(X_test)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test,predictions))

Accuracy: 1.0

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          10       1.00      1.00      1.00     23645
          20       1.00      1.00      1.00     23855
          30       1.00      1.00      1.00     23920
          40       1.00      1.00      1.00     23620

    accuracy                           1.00     95040
   macro avg       1.00      1.00      1.00     95040
weighted avg       1.00      1.00      1.00     95040